[[main]]
url = "/"
name = "Home"
weight = 1

[[main]]
url = "portfolio"
name = "Work"
weight = 2

[[main]]
url = "about"
name = "About"
weight = 3

#[[main]]
#url = "contact"
#name = "Contact"
#weight = 4

#[[main]]
#url = "stuff"
#name = "Blogs and Stuff"
#weight = 5
