logo = ""
firstname = "Ann"
attributes = ["Writer", "Creative Director", "Mother", "Minivan Driver", "Blogger", "Thinker",
"Concepter", "Presenter", "Organizer of Schedules", "Chaos Mitigator", "Wordler"]

## footer
footer_message = "Reach out if you want to work with me"  ## include a message in the footer

## social
footer_socials = true  ## include social icons in footer

[social]
  twitter = "crackyy"
  instagram = ""
  linkedin = "ann-lieberman-7776315"
  workingnotworking = "85-ann"
  email = "annlieberman@gmail.com"
